### ISSUE TITLE
jizhicms1.64 File upload vulnerability (administrative privilege)

### ISSUE THREAD

**Issue by liao10086** [Cherry-toto/jizhicms#10]
1.admin login
2.In basic settings->advanced setting
Attacker can add a php suffix.
<img width="730" alt="1" src="https://user-images.githubusercontent.com/37523122/72243049-cc730000-3625-11ea-9f79-ccbaaf058e37.png">

3.In basic settings->Payment setting
Attacker can upload a php file
<img width="742" alt="2" src="https://user-images.githubusercontent.com/37523122/72243127-0a702400-3626-11ea-8147-9db365ae101d.png">
<img width="1146" alt="3" src="https://user-images.githubusercontent.com/37523122/72243163-24aa0200-3626-11ea-9638-2168f9e92b6c.png">

4.php Code execution
<img width="594" alt="4" src="https://user-images.githubusercontent.com/37523122/72243267-73f03280-3626-11ea-8d31-8d0f3a3020d7.png">

author:zionlab@dbappsecurity.com.cn

**Comment by Cherry-toto** [comment]
系统支持设置上传文件后缀限制，如果你自己设置成php，当然也就能上传php，如果你不设置这个（php）后缀或者不给进入后台的管理员设置上传文件的权限，那么就不会导致这个问题。
系统默认设置是没有添加php后缀的，所以这个是使用者人为造成的安全问题。
就比如，你告诉别人密码，然后别人可以登录后台。
希望你能理解我说的话，我不太会英文，所以，抱歉，让你阅读困难了。
感谢你使用我的系统！
