### ISSUE TITLE
Jizhicms has a CSRF vulnerability that allows for the removal of administrators

### ISSUE THREAD

**Issue by l1523** [Cherry-toto/jizhicms#100]
1. Arriving to the url ：http://192.168.12.128/index.php/admins/Index/index.html 

![image1](https://github.com/user-attachments/assets/fed04738-463c-4868-9a01-3c441852d3f3)

2.  Assuming there are currently 8 administrators, we can enable packet capture for Burp, click delete, and view the data packets 
We can see that a few have been selected here, and we can write more from 2 to 100.
![image2](https://github.com/user-attachments/assets/5b095212-4d82-4192-9dac-f94880fe18d6)

3.	 Use the CSRF creation module of Burp to create CSRF payloads.
 
![image3](https://github.com/user-attachments/assets/77f0d9e1-fd71-4082-ad22-8319459501b3)

4. Open this test connection in the browser, and after automatic submission, it was found that other users were successfully deleted. 

![image4](https://github.com/user-attachments/assets/6d573a0a-5c0f-4423-8206-55bef69a96ba)

![image5](https://github.com/user-attachments/assets/92655778-cb8f-4525-8474-66832ad5a629)

Fix suggestion: Add tokens to restrict this operation.

**Comment by Cherry-toto** [comment]
首先你这个管理员有这个权限，所以才能删除。如果你要防止其他管理员删除这个，将权限收回即可。
