### ISSUE TITLE
错误信息提示： /user/style.htm 

### ISSUE THREAD

**Issue by arkilis** [Cherry-toto/jizhicms#24]
安装完成之后

错误信息提示：
/user/style.html不存在！

**Comment by Cherry-toto** [comment]
伪静态未设置，请参考：http://help.jizhicms.cn/1540682
谢谢您的支持！

**Comment by arkilis** [comment]
谢谢您的回复，能看到后台了，不过验证码还是看不到，有相关的文档吗？十分谢谢


![image](https://user-images.githubusercontent.com/1528028/81459276-72083b80-91e2-11ea-86df-0ac6f2c4326b.png)

**Comment by Cherry-toto** [comment]
你可以加我的QQ：2581047041
我给远程检查看下。
针对验证码看不到的问题，暂时还未出现过。所以无法立刻确定问题所在。
感谢您的使用！

**Comment by arkilis** [comment]
好像是 image url 出了点问题

http://xxxxx/admin.php/Login/vercode.html?0.35431014595680654?0.33620978151575964?0.08518339387111618?0.9440359708155099?0.8423011543995729?0.1793767269244464

`
Fatal error: Uncaught Error: Call to undefined function imagecreatetruecolor() in /home/ben/prod/jizhi/Conf/Functions.php:853 Stack trace: #0 /home/ben/prod/jizhi/A/c/LoginController.php(99): frvercode() #1 [internal function]: A\c\LoginController->vercode('/Login/vercode....', '') #2 /home/ben/prod/jizhi/FrPHP/Fr.php(343): call_user_func_array(Array, Array) #3 /home/ben/prod/jizhi/FrPHP/Fr.php(95): FrPHP\FrPHP->route() #4 /home/ben/prod/jizhi/FrPHP/Fr.php(475): FrPHP\FrPHP->run() #5 /home/ben/prod/jizhi/manyu-dl.php(36): require('/home/ben/prod/...') #6 {main} thrown in /home/ben/prod/jizhi/Conf/Functions.php on line 853`

**Comment by Cherry-toto** [comment]
很显然，这个imagecreatetruecolor函数是存在的，是不是你的PHP版本太低呢？
建议换成php7.0+

**Comment by arkilis** [comment]
是不是我的版本过高？

`ben@iZwz9dmvboi4mj0i3saiz9Z:/etc/nginx/sites-available$ php -v

PHP 7.4.5 (cli) (built: Apr 19 2020 08:42:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies`

**Comment by Cherry-toto** [comment]
那应该是太高了，暂不支持7.4版本

**Comment by arkilis** [comment]
验证码不能加载解决方法：跟作者沟通过，最高支持到 php 7.2

**Debian 9**

`sudo apt-get -y install php7.2-fpm`
`sudo apt-get install php7.2-mysql`
`sudo apt-get install php7.2-gd`
