### ISSUE TITLE
多模块搜索自定义分页

### ISSUE THREAD

**Issue by aURORA-JC** [Cherry-toto/jizhicms#33]
{$listpage}变量在前台值为空
自定义分页错误
在Home/c/HomeController.php - line 872
`$this->pagelist = $arraypage->listpage;`
应改为
`$this->listpage = $arraypage->listpage;`

**Comment by Cherry-toto** [comment]
是的，你写的不错，当初我手残写错了。你前台吧$listpage换成$pagelist即可。谢谢使用！
