### ISSUE TITLE
自定义字段-多附件模块无法上传非图片的文件

### ISSUE THREAD

**Issue by aURORA-JC** [Cherry-toto/jizhicms#34]
在添加多附件字段后，无法上传非图片的文件。

问题原因
文件A/c/FieldsController.php
->line 790 
`,accept:"images"`
->line 792
`,acceptMime:"image/*"`

改写为
`,accept:"file"`
`,acceptMime:"*"`

**Comment by Cherry-toto** [comment]
已知bug，下个版本修复。谢谢提醒。
