### ISSUE TITLE
存储xss

### ISSUE THREAD

**Issue by wind226** [Cherry-toto/jizhicms#68]
在前台文章评论处评论`"><img src=1 onerror=alert(1)>`

![image](https://user-images.githubusercontent.com/24953996/161000017-a8d3e9da-89da-4502-98cf-15d6f8144dc1.png)

管理员后台查看评论可触发xss

![xss](https://user-images.githubusercontent.com/24953996/160998813-6c991ddd-bebe-4941-b046-4581f25f4709.png)

**Comment by Cherry-toto** [comment]
收到，感谢您提供的信息！立马修复!

**Comment by Cherry-toto** [comment]
已发布版本升级修复！
