### ISSUE TITLE
Found a possible security concern

### ISSUE THREAD

**Issue by JamieSlome** [Cherry-toto/jizhicms#69]
Hey there!

I belong to an open source security research community, and a member (@wind226) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Cherry-toto** [comment]
Thank you for your suggestion. I have added `SECURITY.md`, if you have any security related questions, you can send us an email through the contact information inside !

**Comment by JamieSlome** [comment]
Thanks, @Cherry-toto! 👍 

Just for reference, both reports can be found here:
https://huntr.dev/bounties/5719ece1-376a-4726-99f2-d298c36568b2/
https://huntr.dev/bounties/ee55dcde-1434-4297-b7bb-d343d5f1801e/

They are private and only accessible to you. Let me know if you have any questions.

**Comment by Cherry-toto** [comment]
Thank you! Security issues have been fixed!
