### ISSUE TITLE
发表文章存在存储XSS

### ISSUE THREAD

**Issue by wind226** [Cherry-toto/jizhicms#70]
在文章标题写入：`'"><iMg SrC=x OnErRoR=alert(1)>{{7*7}}`
![image](https://user-images.githubusercontent.com/24953996/165454989-3a70ec12-cc31-454f-af6e-3ebcd807f012.png)
后台文章管理处：
![image](https://user-images.githubusercontent.com/24953996/165455133-4e85c2ef-7519-4bb3-8d6b-47958661731b.png)
点击文章标题触发xss：
![image](https://user-images.githubusercontent.com/24953996/165455186-6d78a0ac-536d-4c80-9fef-7aabc28a7e71.png)

**Comment by Cherry-toto** [comment]
查看时并不会触发xss，这个应该是后台的修改功能存在未过滤问题。感谢！我去看看怎么把后台这个问题解决掉。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherry-toto/jizhicms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 下午2:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] 发表文章存在存储XSS (Issue #70)





 
在文章标题写入：'"&gt;<iMg SrC=x OnErRoR=alert(1)&gt;{{7*7}}
 
 后台文章管理处：
 
 点击文章标题触发xss：

**Comment by Cherry-toto** [comment]
再次检查，发现问题出在layui列表回显，会把HTML代码直接输出来，导致的问题。所以，可能不会修复这个问题。感谢提出来！

**Comment by Cherry-toto** [comment]
我再次检查了下，应该是后台layui的回显导致的问题。数据库存储时转译了这个xss代码，layui的显示会把html内容直接显示出来。暂时可以不修复这个问题，再次感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherry-toto/jizhicms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 下午2:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] 发表文章存在存储XSS (Issue #70)





 
在文章标题写入：'"&gt;<iMg SrC=x OnErRoR=alert(1)&gt;{{7*7}}
 
 后台文章管理处：
 
 点击文章标题触发xss：
