### ISSUE TITLE
File allows malicious webshell code to be added

### ISSUE THREAD

**Issue by Kagantua** [Cherry-toto/jizhicms#71]
Find the "Edit Template Online" plugin in the "Plugin Management" section of the backend administration, and proceed to install it.

![image-20220509194416565](https://gitee.com/snikers/picgos/raw/master/202205091944717.png)

Turn on the switch for the plugin and configure it.

![image-20220509194437706](https://gitee.com/snikers/picgos/raw/master/202205091944897.png)

![image-20220509194455177](https://gitee.com/snikers/picgos/raw/master/202205091944809.png)

Then enter the file management interface.

![image-20220509194512067](https://gitee.com/snikers/picgos/raw/master/202205091945030.png)

Open the index.php file, then add the webshell malicious code.

![image-20220509194538555](https://gitee.com/snikers/picgos/raw/master/202205091945972.png)

Open the webshell management tool, enter the URL of the webshell and the corresponding connection password to connect.

![image-20220509194602387](https://gitee.com/snikers/picgos/raw/master/202205091946650.png)

Successful connection.

![image-20220509194627305](https://gitee.com/snikers/picgos/raw/master/202205091946774.png)

**Comment by Cherry-toto** [comment]
Thank you for your advice. It's not a security issue. It's the function of this plug-in! Thank you again!
