### ISSUE TITLE
jizhicms v2.3.3 has a vulnerability, Cross-site request forgery(CSRF)

### ISSUE THREAD

**Issue by believe1808** [Cherry-toto/jizhicms#82]
version: 2.3.3
![image](https://user-images.githubusercontent.com/97570493/198955900-49ef6feb-cdd9-4f4a-9d25-d7845e8b5174.png)
![image](https://user-images.githubusercontent.com/97570493/198955915-287197ea-51a7-406e-ba89-75e32e582391.png)
![image](https://user-images.githubusercontent.com/97570493/198955940-b5a7b414-9646-4059-98ef-30b5dec44275.png)
![image](https://user-images.githubusercontent.com/97570493/198955961-6d670252-c0b4-4c28-b21f-048a23af9b70.png)
![image](https://user-images.githubusercontent.com/97570493/198955973-9237dcbf-4bf8-4545-9702-03498df9f597.png)
![image](https://user-images.githubusercontent.com/97570493/198955998-aaeac13b-bee9-4336-bfa3-485cd1fd9b51.png)

**Comment by Cherry-toto** [comment]
假设后台session被别人拿到，那就存在安全隐患，在此基础上再利用此漏洞做任何其他操作将不被认为是安全问题。
另外，删除功能也要有权限，测试平台你给我删除一个试试？  demo.jizhicms.cn  本身具备有权限，你还要去其他站点操作，这不是脱裤子放屁多此一举？

**Comment by Cherry-toto** [comment]
首先，谢谢你的提醒。
假设后台session被别人拿到，那就存在安全隐患，在此基础上再利用此漏洞做任何其他操作将不被认为是安全问题。
另外，删除功能也要有权限，测试平台你给我删除一个试试？&nbsp; demo.jizhicms.cn&nbsp; 本身具备有删除权限，你还要去其他站点操作，这不是脱裤子放屁多此一举？










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherry-toto/jizhicms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 下午3:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] jizhicms v2.3.3 has a vulnerability, Cross-site request forgery(CSRF) (Issue #82)





 
version: 2.3.3
