### ISSUE TITLE
安装完以后点进入后台没反应

### ISSUE THREAD

**Issue by wf58585858** [Cherry-toto/jizhicms#87]
安装完以后点进入后台没反应
访问 /admin ， /admin.php
都是显示404
这个在nginx 下，没有重写规则啥的吗？

**Comment by Cherry-toto** [comment]
后台地址：/index.php/admins&nbsp;&nbsp;

这里的admins可以在index.php里面修改


伪静态使用thinkphp的伪静态即可（并非thinkphp的框架）


帮助文档：help.jizhicms.cn





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherry-toto/jizhicms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月2日(星期五) 下午5:12
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] 安装完以后点进入后台没反应 (Issue #87)





 
安装完以后点进入后台没反应
 访问 /admin ， /admin.php
 都是显示404
 这个在nginx 下，没有重写规则啥的吗？
