### ISSUE TITLE
screen筛选在php7.2以上版本中报错

### ISSUE THREAD

**Issue by GitHubPangHu** [Cherry-toto/jizhicms#88]
极致cms版本  v2.4.5
用的宝塔，php版本7.4下点击筛选中的选项会报错。
报错原因大概率是**/conf/Functions.php:1276 中的unset()在php7.2之后弃用了**。希望能够修改这个地方让他兼容，我试着把变量赋值null，但是筛选不出结果。具体原因就不懂了。把php版本切换成7.0或者5.6都可以正常筛选。

报错如下

Fatal error
: Uncaught Error: Cannot unset string offsets in /www/wwwroot/*/conf/Functions.php:1276 Stack trace: #0 /www/wwwroot/*/cache/63aa9f534d633ce917e4280c382bccc5.php(387): change_parse_url() #1 /www/wwwroot/*/frphp/lib/View.php(127): include('/www/wwwroot/lh...') #2 /www/wwwroot/*/frphp/lib/View.php(65): frphp\lib\View->template() #3 /www/wwwroot/**/frphp/lib/Controller.php(67): frphp\lib\View->render() #4 /www/wwwroot/*/app/home/c/ScreenController.php(235): frphp\lib\Controller->display() #5 /www/wwwroot/*/frphp/fr.php(335): app\home\c\ScreenController->index() #6 /www/wwwroot/*/frphp/fr.php(94): frphp\frphp->route() #7 /www/wwwroot/*/frphp/fr.php(520): frphp\frphp->run() #8 /www/wwwroot/*/index.php(17): require('/www/wwwroot/lh...') #9 {main} thrown in

**Comment by GitHubPangHu** [comment]
我刚刚测试了，我用php7.2.33版本，也会报错，可能是我的问题吧，我看您的演示站中用的php7.2.33，我在宝塔中安装此版本，也报错，不知道啥问题了，很可能是我代码中哪里有问题吧。。。希望您看到能够帮我分析一下。

**Comment by Cherry-toto** [comment]
有没有可能你的链接错误？我测试过7.0-7.4都没问题的

**Comment by GitHubPangHu** [comment]
这个筛选功能是只能在product 里面进行筛选嘛，我是对自定义的模型和内容模型筛选数据。
在/conf/Functions.php:1276 中的unset()之前输出 var_dump($arr);var_dump($str);发现$arr在非php7.0版本打印输出是字符串。具体打印如下。基于php7.4.33版本。如果用的php7.0版本则显示的是和第二个一样的。（因为发现宝塔面板php低于7.4设置防跨站会失效，所以目前项目不敢使用php7.4以下版本。）

```
1.筛选的article模型
screen-article-1-youxiqufu-2
string(1) "2" string(9) "youxiqufu"

2.筛选的product模型（这个是极致的案例）
screen-product-1-hy-1
 array(1) { ["hy"]=> string(1) "1" } string(2) "hy"
```

极致案例在php7.4下面也是正常的，但是我的两个筛选都是用的非product模型，所以不知道是不是对其他模型的处理存在问题。

**Comment by Cherry-toto** [comment]
多选单选字段配置必须是：英文字符串=数值，这种形式才有效。你要不是这种类型，比如：字符串=字符串这种是不行的。检查下是不是文章从单选转成多选，这个也有可能存在错误。需要重新勾选。

**Comment by GitHubPangHu** [comment]
问题原因找到了。前台SESSION被我关闭了。我看上面说用不到会员模块和纯内容可以关闭，我就给关闭了。（我不懂，以为这个SESSION是只用于会员用户登录记录使用的。）
我把php版本调到8.0他就能报错在screencontroller中的35行“$_SESSION['screen'] = [];” 然后想到这个应该是被我关闭了，我打开之后，筛选就正常了。（希望能在代码里面判断一下这个是否开启，没有开启给一个报错反馈。）

**Comment by Cherry-toto** [comment]
不支持php8.0
&nbsp;


如沐春
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月22日(星期五) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Cherry-toto/jizhicms] screen筛选在php7.2以上版本中报错 (Issue #88)














 
问题原因找到了。前台SESSION被我关闭了。我看上面说用不到会员模块和纯内容可以关闭，我就给关闭了。（我不懂，以为这个SESSION是只用于会员用户登录记录使用的。）
 我把php版本调到8.0他就能报错在screencontroller中的35行“$_SESSION['screen'] = [];” 然后想到这个应该是被我关闭了，我打开之后，筛选就正常了。（希望能在代码里面判断一下这个是否开启，没有开启给一个报错反馈。）

**Comment by GitHubPangHu** [comment]
嗯嗯，我的意思是在8.0的时候我根据他报错找到了问题所在。是后台的设置中 【前台SESSION】被我关闭导致的
