### ISSUE TITLE
安装完毕后，验证码功能无法使用。图片弹不出来

### ISSUE THREAD

**Issue by IIE-Safety** [Cherry-toto/jizhicms#90]
安装完毕后，验证码功能无法使用。图片弹不出来

目前已经在window和linux都安装成功，但是验证码功能貌似启用失败。

![image](https://github.com/Cherry-toto/jizhicms/assets/65028436/2ddf5aad-72cf-4b7a-b5c4-d3f41e6c139f)

除此以外，还发现php8部署，会提示/frphp/fr.php中setcookie函数中两个null参数不安全。不过不是本次主要目的（顺口提一句），修复方案是

```
# 修改前
setcookie('PHPSESSID', $_COOKIE['PHPSESSID'], time() + SessionTime,'/',null,null,true);
# 修改后
setcookie('PHPSESSID', $_COOKIE['PHPSESSID'], time() + SessionTime,'/',‘’,‘’,true);
```

如果看见，想问问验证码的问题如何修复~

**Comment by Cherry-toto** [comment]
只兼容到7.4



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Cherry-toto/jizhicms] 安装完毕后，验证码功能无法使用。图片弹不出来 (Issue #90)




 
安装完毕后，验证码功能无法使用。图片弹不出来
 
目前已经在window和linux都安装成功，但是验证码功能貌似启用失败。
 
image.png (view on web)
 
除此以外，还发现php8部署，会提示/frphp/fr.php中setcookie函数中两个null参数不安全。不过不是本次主要目的（顺口提一句），修复方案是
 # 修改前 setcookie('PHPSESSID', $_COOKIE['PHPSESSID'], time() + SessionTime,'/',null,null,true); # 修改后 setcookie('PHPSESSID', $_COOKIE['PHPSESSID'], time() + SessionTime,'/',‘’,‘’,true);  
如果看见，想问问验证码的问题如何修复~

**Comment by IIE-Safety** [comment]
嗯嗯，是的。现在使用php7.3，验证码功能似乎启动不了

**Comment by Cherry-toto** [comment]
推荐宝塔部署，可能伪静态没配置好，或者image模块没有安装



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cherry-toto/jizhicms] 安装完毕后，验证码功能无法使用。图片弹不出来 (Issue #90)




 
嗯嗯，是的。现在使用php7.3，验证码功能似乎启动不了

**Comment by IIE-Safety** [comment]
好的，谢谢

**Comment by Cherry-toto** [comment]
请下载最新版本进行升级。推荐下载地址：http://down.jizhicms.cn/jizhicms.zip
这个下载地址会一直保持最新版本。目前主要是gitee里面更新，github比较少更新。
请悉知！
