### ISSUE TITLE
新版本导致的错误？

### ISSUE THREAD

**Issue by xinjilianmeng** [Cherry-toto/jizhicms#92]
SELECT SQL_CALC_FOUND_ROWS * FROM jz_classtype WHERE isshow=1 and (tid in (1) or tids like '%,1,%' ) ORDER BY orders desc,addtime desc,id desc LIMIT 10
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tid' in 'where clause' in /www/wwwroot/peso.net/frphp/db/DBholder.php:57 Stack trace: #0 /www/wwwroot/peso.net/frphp/db/DBholder.php(57): PDO->query() #1 /www/wwwroot/peso.net/frphp/db/DBholder.php(74): frphp\db\DBholder->query() #2 /www/wwwroot/peso.net/frphp/lib/Model.php(264): frphp\db\DBholder->getArray() #3 /www/wwwroot/peso.net/frphp/extend/Page.php(335): frphp\lib\Model->findPage() #4 /www/wwwroot/peso.net/app/home/c/HomeController.php(249): frphp\extend\Page->go() #5 /www/wwwroot/peso.net/frphp/fr.php(335): app\home\c\HomeController->jizhi() #6 /www/wwwroot/peso.net/frphp/fr.php(94): frphp\frphp->route() #7 /www/wwwroot/peso.net/frphp/fr.php(520): frphp\frphp->run() #8 /www/wwwroot/peso.net/index.php(17): require('...') #9 {main} thrown in /www/wwwroot/peso.net/frphp/db/DBholder.php on line 57

**Comment by Cherry-toto** [comment]
你在模板中写错了吧。
