### ISSUE TITLE
A XSS vulnerability was found in the message function of jizhicms V2.5.1 

### ISSUE THREAD

**Issue by Yohane-nlm** [Cherry-toto/jizhicms#93]
At the URL http://xxx/contact.html , which is a contact page, we could find a 'leave a message' function. Fill the form with a xss payload `<img src onerror=_=alert,_(13232)>` as showd below and submit it.

<img width="976" alt="截屏2024-04-28 20 55 21" src="https://github.com/Cherry-toto/jizhicms/assets/12543315/584e8a07-bba5-45a1-b1bb-ac8461d81bb4">

Then if we go to the admin page of the cms, we could find the message can be seen in the index of the admin page with a 'reply' button on the bottom right corner.

<img width="1416" alt="截屏2024-04-28 20 57 45" src="https://github.com/Cherry-toto/jizhicms/assets/12543315/a4f5d943-8fbb-4cb1-ae3c-1cebc5cbdf35">

if we click the 'reply' button, the xss payload will be excuted

<img width="1414" alt="截屏2024-04-28 20 58 24" src="https://github.com/Cherry-toto/jizhicms/assets/12543315/f7af44ca-c2c2-4da7-ab9b-f73c564d880b">

**Comment by Cherry-toto** [comment]
Thank you for the issue , next version will fix this error.







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Cherry-toto/jizhicms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月28日(星期天) 晚上9:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Cherry-toto/jizhicms] A XSS vulnerability was found in the message function of jizhicms V2.5.1  (Issue #93)





 
At the URL http://xxx/contact.html , which is a contact page, we could find a 'leave a message' function. Fill the form with a xss payload as showd below and submit it.
 2024-04-28.20.55.21.png (view on web) 
Then if we go to the admin page of the cms, we could find the message can be seen in the index of the admin page with a 'reply' button on the bottom right corner.
 2024-04-28.20.57.45.png (view on web) 
if we click the 'reply' button, the xss payload will be excuted
 2024-04-28.20.58.24.png (view on web)
